name: Generate Snake

on:
  # 每天午夜自动运行
  schedule:
    - cron: "0 0 * * *" 
  # 允许手动触发
  workflow_dispatch:
  
  # 每当 push 到 master/main 分支时也会运行 (可选)
  # push:
  #   branches:
  #   - master
  #   - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # 你的 GitHub 用户名
          github_user_name: ${{ github.repository_owner }}
          
          # 生成的文件列表 (这里生成了普通版和深色模式版)
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # 将生成的文件推送到 output 分支，避免污染主分支
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
